use std::{env, fs, path::PathBuf};

const CA_SERVICE_ENV: &str = "DHTTP_CA_SERVICE";
const DEFAULT_CA_SERVICE: &str = "https://api.genmeta.net";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let ca_service = env_or_default(CA_SERVICE_ENV, DEFAULT_CA_SERVICE);

    let bootstrap = format!(
        "// @generated by build.rs; do not edit.\n\
         pub const DHTTP_CA_SERVICE: &str = {ca_service:?};\n"
    );
    fs::write(out_dir.join("bootstrap.rs"), bootstrap)
        .expect("failed to write generated genmeta identity bootstrap constants");

    println!("cargo::rerun-if-env-changed={CA_SERVICE_ENV}");
}

fn env_or_default(name: &str, default: &str) -> String {
    env::var(name).unwrap_or_else(|_| default.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_env_uses_genmeta_production_server() {
        let name = format!(
            "__GENMETA_IDENTITY_MISSING_BOOTSTRAP_{}",
            std::process::id()
        );

        assert_eq!(
            env_or_default(&name, DEFAULT_CA_SERVICE),
            "https://api.genmeta.net"
        );
    }
}
