use std::{env, fs, path::PathBuf};

const CERT_SERVER_URL_ENV: &str = "DHTTP_CERT_SERVER_URL";
const DEFAULT_CERT_SERVER_BASE_URL: &str = "https://license.genmeta.net";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let cert_server_url = env_or_default(CERT_SERVER_URL_ENV, DEFAULT_CERT_SERVER_BASE_URL);

    let bootstrap = format!(
        "// @generated by build.rs; do not edit.\n\
         pub const DHTTP_CERT_SERVER_URL: &str = {cert_server_url:?};\n"
    );
    fs::write(out_dir.join("bootstrap.rs"), bootstrap)
        .expect("failed to write generated genmeta identity bootstrap constants");

    println!("cargo::rerun-if-env-changed={CERT_SERVER_URL_ENV}");
}

fn env_or_default(name: &str, default: &str) -> String {
    env::var(name).unwrap_or_else(|_| default.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_env_uses_license_server() {
        let name = format!(
            "__GENMETA_IDENTITY_MISSING_BOOTSTRAP_{}",
            std::process::id()
        );

        assert_eq!(
            env_or_default(&name, DEFAULT_CERT_SERVER_BASE_URL),
            "https://license.genmeta.net"
        );
    }
}
