[env]
DHTTP_BOOTSTRAP_URL = "https://bootstrap.genmeta.net:20002"
DHTTP_CERT_SERVER_URL = "https://api.genmeta.net:4433"
DHTTP_H3_DNS_SERVER = "https://ddns.genmeta.net:4433"
DHTTP_MDNS_SERVICE = "_dhttp.local"
DHTTP_ROOT_CA = { value = "keychain/root.crt", relative = true }

[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"

[target.x86_64-unknown-linux-gnu]
strip = { path = "llvm-strip" }

[target.aarch64-unknown-linux-musl]
strip = { path = "llvm-strip" }

[target.i686-unknown-linux-musl]
strip = { path = "llvm-strip" }

[target.armv7-unknown-linux-musleabihf]
strip = { path = "llvm-strip" }
