[env]
DHTTP_ROOT_CA = { value = "keychain/root.crt", relative = true }

[alias]
xtask = "run --package xtask --"

[target.x86_64-unknown-linux-gnu]
strip = { path = "llvm-strip" }

[target.aarch64-unknown-linux-musl]
strip = { path = "llvm-strip" }

[target.i686-unknown-linux-musl]
strip = { path = "llvm-strip" }

[target.armv7-unknown-linux-musleabihf]
strip = { path = "llvm-strip" }
